[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_ico = "44nzPiCy17Ld9e664MvfZyG4SnvJZFYpxSHvti9ArwXJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/abdullah/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
